global.SITUATION_STATUS_ENABLED = 1;
global.SITUATION_STATUS_TESTING = 2;

global.MENUBACKGROUND_STATUS_ENABLED = 1;
global.MENUBACKGROUND_STATUS_DISABLED = 0;

global.PICKUP_STATUS_ENABLED = 1;
global.PICKUP_STATUS_DISABLED = 0;

global.TOPIC_STATUS_ENABLED = 1;
